<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';
import {ElMessage,ElMessageBox} from 'element-plus';
import {Edit,Plus,Search,Delete} from '@element-plus/icons-vue';
import {api,RequestError} from './api';
import type {CropProfile} from '../../server/domain';

const props=defineProps<{locale:'zh'|'uz';devices:{cropId:string}[]}>();
const emit=defineEmits<{changed:[]}>();
const profiles=ref<CropProfile[]>([]),search=ref(''),loading=ref(true),saving=ref(false),dialogOpen=ref(false),editingId=ref('');
type FormProfile=Omit<CropProfile,'version'|'updatedAt'>;
const blank=():FormProfile=>({id:'',nameZh:'',nameUz:'',nameEn:'',category:'',temperature:{min:5,optimalMin:15,optimalMax:25,max:35},moisture:{critical:35,targetMin:55,targetMax:75,max:90},lightHours:{min:10,max:14},irrigation:{maxVolume:80,minIntervalMinutes:120}});
const form=ref<FormProfile>(blank());
const text=computed(()=>props.locale==='zh'?{
 title:'作物参数管理',subtitle:'集中维护作物环境阈值，总览与灌溉决策将实时读取这里的数据',add:'新增作物',profiles:'作物档案',assigned:'已分配分区',updated:'最近更新',search:'搜索作物名称',crop:'作物',category:'类别',temperature:'适宜温度',moisture:'目标湿度',light:'光照时长',irrigation:'单次上限',zones:'分区',actions:'操作',edit:'编辑',remove:'删除',dialogEdit:'编辑作物参数',dialogAdd:'新增作物参数',cancel:'取消',save:'保存参数',identity:'基础信息',limits:'环境阈值',strategy:'灌溉策略',id:'作物编号',nameZh:'中文名称',nameUz:'乌兹别克语名称',nameEn:'英文名称',tempBoundary:'温度告警边界',tempOptimal:'适宜温度范围',moistureCritical:'湿度临界值',moistureTarget:'目标湿度范围',moistureMax:'湿度上限',lightRange:'每日光照',volume:'单次最大水量',interval:'最短间隔',minutes:'分钟',confirm:'确定删除该作物参数吗？',saved:'参数已保存',deleted:'作物参数已删除'}:{
 title:'Ekin parametrlarini boshqarish',subtitle:'Ekin chegaralarini boshqaring; umumiy ko‘rinish va sug‘orish qarorlari shu ma’lumotlarni o‘qiydi',add:'Ekin qo‘shish',profiles:'Ekin profillari',assigned:'Biriktirilgan hududlar',updated:'So‘nggi yangilanish',search:'Ekin nomini qidiring',crop:'Ekin',category:'Toifa',temperature:'Mos harorat',moisture:'Maqsad namlik',light:'Yoritish vaqti',irrigation:'Bir martalik limit',zones:'Hudud',actions:'Amallar',edit:'Tahrirlash',remove:'O‘chirish',dialogEdit:'Ekin parametrlarini tahrirlash',dialogAdd:'Yangi ekin parametrlari',cancel:'Bekor qilish',save:'Saqlash',identity:'Asosiy ma’lumot',limits:'Muhit chegaralari',strategy:'Sug‘orish strategiyasi',id:'Ekin ID',nameZh:'Xitoycha nomi',nameUz:'O‘zbekcha nomi',nameEn:'Inglizcha nomi',tempBoundary:'Harorat chegaralari',tempOptimal:'Mos harorat oralig‘i',moistureCritical:'Kritik namlik',moistureTarget:'Maqsad namlik oralig‘i',moistureMax:'Namlik yuqori chegarasi',lightRange:'Kunlik yoritish',volume:'Maksimal suv hajmi',interval:'Minimal interval',minutes:'daqiqa',confirm:'Bu ekin parametrlarini o‘chirasizmi?',saved:'Parametrlar saqlandi',deleted:'Ekin parametrlari o‘chirildi'});
const filtered=computed(()=>{const query=search.value.trim().toLowerCase();return query?profiles.value.filter(item=>[item.nameZh,item.nameUz,item.nameEn,item.id,item.category].some(value=>value.toLowerCase().includes(query))):profiles.value;});
const assignedCount=(id:string)=>props.devices.filter(device=>device.cropId===id).length;
const lastUpdated=computed(()=>profiles.value.length?new Date(Math.max(...profiles.value.map(item=>+new Date(item.updatedAt)))).toLocaleString(props.locale==='zh'?'zh-CN':'uz-UZ'):'--');
const cropName=(item:CropProfile)=>props.locale==='zh'?item.nameZh:item.nameUz;
function errorText(error:unknown){return error instanceof RequestError?error.message:'Operation failed';}
async function load(){loading.value=true;try{profiles.value=await api<CropProfile[]>('/crop-profiles');}catch(error){ElMessage.error(errorText(error));}finally{loading.value=false;}}
function openCreate(){editingId.value='';form.value=blank();dialogOpen.value=true;}
function openEdit(item:CropProfile){editingId.value=item.id;form.value=structuredClone({id:item.id,nameZh:item.nameZh,nameUz:item.nameUz,nameEn:item.nameEn,category:item.category,temperature:item.temperature,moisture:item.moisture,lightHours:item.lightHours,irrigation:item.irrigation});dialogOpen.value=true;}
async function save(){saving.value=true;try{if(editingId.value)await api(`/crop-profiles/${editingId.value}`,form.value,'PUT');else await api('/crop-profiles',form.value,'POST');dialogOpen.value=false;await load();emit('changed');ElMessage.success(text.value.saved);}catch(error){ElMessage.error(errorText(error));}finally{saving.value=false;}}
async function remove(item:CropProfile){try{await ElMessageBox.confirm(text.value.confirm,`${text.value.remove} / Delete`,{type:'warning',confirmButtonText:text.value.remove,cancelButtonText:text.value.cancel});await api(`/crop-profiles/${item.id}`,undefined,'DELETE');await load();emit('changed');ElMessage.success(text.value.deleted);}catch(error){if(error!=='cancel'&&error!=='close')ElMessage.error(errorText(error));}}
onMounted(load);
</script>

<template><main class="crop-management"><header class="management-header"><div><p class="eyebrow">AGRONOMIC CONFIGURATION</p><h1>{{text.title}} <small>Crop Parameter Management</small></h1><p>{{text.subtitle}}</p></div><button class="add-crop-button" @click="openCreate"><el-icon><Plus/></el-icon><span><b>{{text.add}}</b><small>Add Crop Profile</small></span></button></header>
 <section class="management-stats"><article><span>{{profiles.length}}</span><p><b>{{text.profiles}}</b><small>Crop Profiles</small></p></article><article><span>{{devices.length}}</span><p><b>{{text.assigned}}</b><small>Assigned Zones</small></p></article><article><span class="date-value">{{lastUpdated}}</span><p><b>{{text.updated}}</b><small>Last Updated</small></p></article></section>
 <section class="profile-table-card"><div class="table-tools"><div><h2>{{text.profiles}} <small>/ Crop Profiles</small></h2><p>数据库持久化 · Database persisted · {{profiles.length}} profiles</p></div><label class="profile-search"><el-icon><Search/></el-icon><input v-model="search" :placeholder="`${text.search} / Search`"></label></div>
  <el-table v-loading="loading" :data="filtered" class="profile-table" row-key="id"><el-table-column min-width="190"><template #header><b>{{text.crop}}</b><small>Crop</small></template><template #default="{row}"><div class="crop-cell"><span>{{cropName(row)}}</span><b>{{row.nameEn}}</b><small># {{row.id}}</small></div></template></el-table-column><el-table-column min-width="155"><template #header><b>{{text.category}}</b><small>Category</small></template><template #default="{row}">{{row.category}}</template></el-table-column><el-table-column min-width="140"><template #header><b>{{text.temperature}}</b><small>Optimal Temperature</small></template><template #default="{row}"><strong>{{row.temperature.optimalMin}}–{{row.temperature.optimalMax}}°C</strong><small class="boundary">{{row.temperature.min}}–{{row.temperature.max}}°C boundary</small></template></el-table-column><el-table-column min-width="140"><template #header><b>{{text.moisture}}</b><small>Target Moisture</small></template><template #default="{row}"><strong class="green-text">{{row.moisture.targetMin}}–{{row.moisture.targetMax}}%</strong><small class="boundary">critical {{row.moisture.critical}}%</small></template></el-table-column><el-table-column min-width="120"><template #header><b>{{text.light}}</b><small>Light Hours</small></template><template #default="{row}">{{row.lightHours.min}}–{{row.lightHours.max}} h/day</template></el-table-column><el-table-column min-width="110"><template #header><b>{{text.irrigation}}</b><small>Max Volume</small></template><template #default="{row}">{{row.irrigation.maxVolume}} mL</template></el-table-column><el-table-column min-width="80" align="center"><template #header><b>{{text.zones}}</b><small>Zones</small></template><template #default="{row}"><span class="zone-count">{{assignedCount(row.id)}}</span></template></el-table-column><el-table-column min-width="145" fixed="right" align="right"><template #header><b>{{text.actions}}</b><small>Actions</small></template><template #default="{row}"><button class="row-action" @click="openEdit(row)"><el-icon><Edit/></el-icon>{{text.edit}}</button><button class="row-action danger" :disabled="assignedCount(row.id)>0" @click="remove(row)"><el-icon><Delete/></el-icon>{{text.remove}}</button></template></el-table-column></el-table>
 </section>
 <el-dialog v-model="dialogOpen" width="760px" class="crop-dialog" :close-on-click-modal="false"><template #header><div class="dialog-heading"><b>{{editingId?text.dialogEdit:text.dialogAdd}}</b><small>{{editingId?'Edit Crop Parameters':'Add Crop Parameters'}}</small></div></template><el-form label-position="top" @submit.prevent="save"><h3>{{text.identity}} <small>/ Identity</small></h3><div class="form-grid four"><el-form-item :label="`${text.id} / Crop ID`"><el-input v-model="form.id" :disabled="Boolean(editingId)" placeholder="e.g. lettuce"/></el-form-item><el-form-item :label="`${text.nameZh} / Chinese`"><el-input v-model="form.nameZh"/></el-form-item><el-form-item :label="`${text.nameUz} / Uzbek`"><el-input v-model="form.nameUz"/></el-form-item><el-form-item :label="`${text.nameEn} / English`"><el-input v-model="form.nameEn"/></el-form-item></div><el-form-item :label="`${text.category} / Category`"><el-input v-model="form.category"/></el-form-item><h3>{{text.limits}} <small>/ Environmental Thresholds</small></h3><div class="form-grid four"><el-form-item :label="`${text.tempBoundary} Min`"><el-input-number v-model="form.temperature.min" :controls="false"/></el-form-item><el-form-item label="Optimal Min °C"><el-input-number v-model="form.temperature.optimalMin" :controls="false"/></el-form-item><el-form-item label="Optimal Max °C"><el-input-number v-model="form.temperature.optimalMax" :controls="false"/></el-form-item><el-form-item :label="`${text.tempBoundary} Max`"><el-input-number v-model="form.temperature.max" :controls="false"/></el-form-item><el-form-item :label="`${text.moistureCritical} / Critical %`"><el-input-number v-model="form.moisture.critical" :controls="false"/></el-form-item><el-form-item label="Target Min %"><el-input-number v-model="form.moisture.targetMin" :controls="false"/></el-form-item><el-form-item label="Target Max %"><el-input-number v-model="form.moisture.targetMax" :controls="false"/></el-form-item><el-form-item :label="`${text.moistureMax} / Maximum %`"><el-input-number v-model="form.moisture.max" :controls="false"/></el-form-item><el-form-item label="Light Min h/day"><el-input-number v-model="form.lightHours.min" :controls="false"/></el-form-item><el-form-item label="Light Max h/day"><el-input-number v-model="form.lightHours.max" :controls="false"/></el-form-item></div><h3>{{text.strategy}} <small>/ Irrigation Strategy</small></h3><div class="form-grid two"><el-form-item :label="`${text.volume} / Max Volume (mL)`"><el-input-number v-model="form.irrigation.maxVolume" :controls="false"/></el-form-item><el-form-item :label="`${text.interval} / Min Interval (${text.minutes})`"><el-input-number v-model="form.irrigation.minIntervalMinutes" :controls="false"/></el-form-item></div></el-form><template #footer><button class="dialog-cancel" @click="dialogOpen=false">{{text.cancel}} / Cancel</button><button class="dialog-save" :disabled="saving" @click="save">{{text.save}} / Save</button></template></el-dialog>
</main></template>
