<script setup lang="ts">
import {computed,nextTick,onMounted,ref,watch} from 'vue';
import {ElMessage,ElMessageBox} from 'element-plus';
import {ChatDotRound,Check,Connection,DataAnalysis,Document,Loading,Promotion,Refresh,Sunny,Warning} from '@element-plus/icons-vue';
import {api,RequestError} from './api';
import type {CropProfile,Device,Message,Task} from '../../server/domain';

type Locale='zh'|'uz';
type PublicDevice=Device&{sampleCount:number};
type Recommendation={deviceId:string;crop:string;currentMoisture:number;targetMoisture:number;maxVolume:number;reason:string};
type Analysis={scope:string;at:string;model:string;summary:{total:number;online:number;dry:number;irrigating:number};recommendations:Recommendation[];warnings:string[];sources:{key:string;label:string;en:string}[]};
type KnowledgeResponse={messages:Message[];analysis:Analysis};
const props=defineProps<{locale:Locale;devices:PublicDevice[];profiles:CropProfile[];tasks:Task[];aiConfigured:boolean}>();
const emit=defineEmits<{execute:[{ids:string[];kind:'bulk'}]}>();

const scope=ref('all'),question=ref(''),sending=ref(false),loadingHistory=ref(false),messages=ref<Message[]>([]),analysis=ref<Analysis>(),chatBody=ref<HTMLElement>();
const copy=computed(()=>props.locale==='zh'?{
 title:'知识融合',subtitle:'融合实时感知、作物知识与历史趋势的灌溉智能助手',assistant:'灌溉智能助手',online:'DeepSeek 已连接',offline:'DeepSeek 未配置',scope:'分析范围',all:'全部 16 个分区',welcome:'您好，我是灌溉知识融合助手。可以询问缺水原因、分区对比或生成今日参考方案。',placeholder:'例如：结合当前数据，为缺水分区生成灌溉建议……',send:'发送',thinking:'正在融合数据与农业知识',evidence:'本次融合依据',plan:'参考灌溉方案',execute:'确认并创建闭环灌溉任务',noPlan:'当前没有满足安全规则的待灌溉分区',notice:'模型提供参考建议；所有控制指令均需操作员确认，并由安全规则再次校验。',warnings:'风险与限制',current:'当前',target:'目标',limit:'安全上限',confirmTitle:'确认执行参考方案',confirmText:'即将为以下分区创建闭环灌溉任务：',confirmButton:'确认创建',cancel:'取消',confirmed:'方案已提交，系统将按目标湿度闭环控制',history:'对话记录',refresh:'刷新上下文'
}:{
 title:'Bilimlarni birlashtirish',subtitle:'Jonli sensorlar, ekin bilimlari va tarixiy tendensiyalarni birlashtiruvchi sug‘orish yordamchisi',assistant:'Sug‘orish aqlli yordamchisi',online:'DeepSeek ulangan',offline:'DeepSeek sozlanmagan',scope:'Tahlil doirasi',all:'Barcha 16 hudud',welcome:'Salom, men sug‘orish bo‘yicha bilimlarni birlashtiruvchi yordamchiman. Suv tanqisligi, hududlarni solishtirish yoki kunlik reja haqida so‘rashingiz mumkin.',placeholder:'Masalan: joriy ma’lumotlar asosida sug‘orish rejasini tuzing…',send:'Yuborish',thinking:'Ma’lumotlar va agro-bilimlar birlashtirilmoqda',evidence:'Birlashtirish manbalari',plan:'Tavsiya etilgan reja',execute:'Tasdiqlash va yopiq siklli vazifa yaratish',noPlan:'Xavfsizlik qoidalariga mos sug‘oriladigan hudud yo‘q',notice:'Model tavsiya beradi; boshqaruv buyruqlari operator tomonidan tasdiqlanadi va xavfsizlik qoidalari bilan qayta tekshiriladi.',warnings:'Xatar va cheklovlar',current:'Joriy',target:'Maqsad',limit:'Xavfsiz limit',confirmTitle:'Rejani bajarishni tasdiqlang',confirmText:'Quyidagi hududlar uchun yopiq siklli vazifa yaratiladi:',confirmButton:'Tasdiqlash',cancel:'Bekor qilish',confirmed:'Reja yuborildi, tizim maqsad namligigacha boshqaradi',history:'Suhbat tarixi',refresh:'Kontekstni yangilash'
});
const presets=computed(()=>props.locale==='zh'?['哪些分区现在需要灌溉？','为全部缺水分区生成今日灌溉方案','比较各分区湿度并说明风险','为什么不能只根据单次湿度读数灌溉？']:['Hozir qaysi hududlarni sug‘orish kerak?','Quruq hududlar uchun bugungi rejani tuzing','Hududlar namligini taqqoslab, xatarlarni ayting','Nega faqat bitta namlik qiymati yetarli emas?']);
const selectedDevice=computed(()=>props.devices.find(device=>device.id===scope.value));
const selectedProfile=computed(()=>selectedDevice.value?props.profiles.find(profile=>profile.id===selectedDevice.value!.cropId):undefined);
const activeCount=computed(()=>props.tasks.filter(task=>['pending','running'].includes(task.status)).length);
function errorText(error:unknown){return error instanceof RequestError?error.message:(props.locale==='zh'?'请求失败，请稍后重试':'So‘rov bajarilmadi');}
function cleanContent(content:string){return content.replace(/\*\*/g,'').replace(/^#{1,4}\s*/gm,'');}
async function scrollBottom(){await nextTick();chatBody.value?.scrollTo({top:chatBody.value.scrollHeight,behavior:'smooth'});}
async function loadHistory(){loadingHistory.value=true;try{messages.value=await api<Message[]>(`/knowledge/conversations/${scope.value}`);await scrollBottom();}catch(error){ElMessage.error(errorText(error));}finally{loadingHistory.value=false;}}
async function ask(value?:string){const text=(value??question.value).trim();if(!text||sending.value||!props.aiConfigured)return;question.value='';messages.value.push({id:crypto.randomUUID(),deviceId:`knowledge:${scope.value}`,role:'user',content:text,at:new Date().toISOString(),lang:props.locale,mode:'real'});sending.value=true;await scrollBottom();try{const response=await api<KnowledgeResponse>('/knowledge/chat',{scope:scope.value,question:text,lang:props.locale});messages.value.splice(-1,1,...response.messages);analysis.value=response.analysis;await scrollBottom();}catch(error){messages.value.pop();question.value=text;ElMessage.error(errorText(error));}finally{sending.value=false;}}
async function executePlan(){const ids=analysis.value?.recommendations.map(item=>item.deviceId)??[];if(!ids.length)return;try{await ElMessageBox.confirm(`${copy.value.confirmText} ${ids.join('、')}`,copy.value.confirmTitle,{confirmButtonText:copy.value.confirmButton,cancelButtonText:copy.value.cancel,type:'warning'});emit('execute',{ids,kind:'bulk'});}catch{/* operator cancelled */}}
watch(scope,()=>{analysis.value=undefined;loadHistory();});onMounted(loadHistory);
</script>

<template><main class="knowledge-page">
 <header class="knowledge-header"><div><p>KNOWLEDGE FUSION CENTER</p><h1>{{copy.title}} <small>Knowledge Fusion</small></h1><span>{{copy.subtitle}}</span></div><div :class="['model-state',{offline:!aiConfigured}]"><i></i><p><b>DeepSeek Chat</b><small>{{aiConfigured?copy.online:copy.offline}}</small></p></div></header>
 <section class="fusion-layout">
  <div class="fusion-chat">
   <header class="chat-toolbar"><div class="assistant-title"><span><el-icon><ChatDotRound/></el-icon></span><p><b>{{copy.assistant}}</b><small>Irrigation Copilot · DeepSeek</small></p></div><label><span>{{copy.scope}}<small>Analysis Scope</small></span><select v-model="scope"><option value="all">{{copy.all}}</option><option v-for="device in devices" :key="device.id" :value="device.id">{{device.id}} · {{locale==='zh'?device.name:device.nameEn}}</option></select></label><button :title="copy.refresh" @click="loadHistory"><el-icon :class="{'is-loading':loadingHistory}"><Refresh/></el-icon></button></header>
   <div ref="chatBody" class="chat-body">
    <div v-if="!messages.length" class="assistant-welcome"><span><img src="/leaf-logo.png" alt=""></span><div><b>{{copy.assistant}}</b><p>{{copy.welcome}}</p><div class="prompt-chips"><button v-for="item in presets" :key="item" @click="ask(item)">{{item}}</button></div></div></div>
    <article v-for="message in messages" :key="message.id" :class="['chat-message',message.role]"><span v-if="message.role==='assistant'" class="message-avatar"><img src="/leaf-logo.png" alt=""></span><div><small>{{message.role==='assistant'?copy.assistant:(locale==='zh'?'操作员':'Operator')}}</small><p>{{cleanContent(message.content)}}</p><time>{{new Date(message.at).toLocaleTimeString(locale==='zh'?'zh-CN':'uz-UZ',{hour:'2-digit',minute:'2-digit'})}}</time></div></article>
    <article v-if="sending" class="chat-message assistant thinking"><span class="message-avatar"><el-icon class="is-loading"><Loading/></el-icon></span><div><small>DeepSeek</small><p>{{copy.thinking}}<i></i><i></i><i></i></p></div></article>
   </div>
   <footer class="chat-input"><textarea v-model="question" :placeholder="copy.placeholder" maxlength="1200" @keydown.enter.exact.prevent="ask()"></textarea><div><span>{{question.length}} / 1200</span><button :disabled="!question.trim()||sending||!aiConfigured" @click="ask()"><el-icon><Promotion/></el-icon>{{copy.send}}<small>Send</small></button></div></footer>
  </div>
  <aside class="fusion-context">
   <section class="context-card live-context"><header><div><el-icon><Connection/></el-icon><span><b>{{locale==='zh'?'实时上下文':'Jonli kontekst'}}</b><small>Live Database Context</small></span></div><em>{{scope==='all'?devices.length:1}} {{locale==='zh'?'分区':'hudud'}}</em></header><div v-if="scope==='all'" class="context-stats"><span><strong>{{devices.filter(d=>d.online).length}}</strong><small>Online</small></span><span><strong>{{devices.filter(d=>d.online&&d.moisture<(profiles.find(p=>p.id===d.cropId)?.moisture.targetMin??0)).length}}</strong><small>Water Required</small></span><span><strong>{{activeCount}}</strong><small>Irrigating</small></span></div><div v-else-if="selectedDevice&&selectedProfile" class="selected-context"><b>{{selectedDevice.id}} · {{locale==='zh'?selectedProfile.nameZh:selectedProfile.nameUz}}</b><p><span>{{selectedDevice.moisture.toFixed(0)}}%</span><small>{{selectedProfile.moisture.targetMin}}–{{selectedProfile.moisture.targetMax}}% Target</small></p><p><span>{{selectedDevice.temperature}}°C</span><small>{{selectedProfile.temperature.optimalMin}}–{{selectedProfile.temperature.optimalMax}}°C Optimal</small></p></div></section>
   <section class="context-card evidence-sources"><header><div><el-icon><DataAnalysis/></el-icon><span><b>{{copy.evidence}}</b><small>Fusion Evidence</small></span></div></header><ul><li v-for="source in (analysis?.sources??[{key:'sensor',label:'实时传感器数据',en:'Live sensor readings'},{key:'profile',label:'作物参数知识库',en:'Crop profile knowledge base'},{key:'history',label:'12 小时时序趋势',en:'12-hour time-series trend'},{key:'task',label:'灌溉任务与设备状态',en:'Irrigation and device state'}])" :key="source.key"><el-icon><Check/></el-icon><span><b>{{locale==='zh'?source.label:source.en}}</b><small>{{source.en}}</small></span></li></ul></section>
   <section class="context-card plan-card"><header><div><el-icon><Document/></el-icon><span><b>{{copy.plan}}</b><small>Reference Irrigation Plan</small></span></div><em v-if="analysis">{{analysis.recommendations.length}}</em></header><div v-if="analysis?.recommendations.length" class="recommendations"><article v-for="item in analysis.recommendations" :key="item.deviceId"><div><strong>{{item.deviceId}}</strong><p><b>{{item.crop}}</b><small>{{item.reason}}</small></p></div><dl><div><dt>{{copy.current}}</dt><dd>{{item.currentMoisture}}%</dd></div><div><dt>{{copy.target}}</dt><dd>{{item.targetMoisture}}%</dd></div><div><dt>{{copy.limit}}</dt><dd>{{item.maxVolume}} mL</dd></div></dl></article><button class="execute-plan" @click="executePlan"><el-icon><Sunny/></el-icon><span><b>{{copy.execute}}</b><small>Operator Confirmation Required</small></span></button></div><div v-else class="empty-plan">{{copy.noPlan}}<small>No executable recommendation yet</small></div></section>
   <section v-if="analysis?.warnings.length" class="context-card warning-card"><header><div><el-icon><Warning/></el-icon><span><b>{{copy.warnings}}</b><small>Risks &amp; Constraints</small></span></div></header><ul><li v-for="warning in analysis.warnings" :key="warning">{{warning}}</li></ul></section>
   <p class="fusion-notice"><el-icon><Warning/></el-icon>{{copy.notice}}</p>
  </aside>
 </section>
</main></template>
