<script setup lang="ts">
import {onBeforeUnmount,onMounted,ref,watch} from 'vue';
import * as echarts from 'echarts';
import type {Device} from '../../server/domain';
const props=defineProps<{device:Device&{sampleCount:number}}>();
const root=ref<HTMLElement>();let chart:echarts.ECharts|undefined,observer:ResizeObserver|undefined;
function render(){if(!chart)return;const points=props.device.history.length?props.device.history:[{at:props.device.lastSeen,value:props.device.moisture}];const values=points.map(point=>point.value),labels=points.map(point=>new Date(point.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}));const current=values.at(-1)??props.device.moisture;chart.setOption({animationDuration:280,grid:{left:45,right:24,top:20,bottom:31},tooltip:{trigger:'axis',textStyle:{fontSize:13},valueFormatter:(value:unknown)=>`${Number(value).toFixed(1)}%`},xAxis:{type:'category',boundaryGap:false,data:labels,axisLine:{lineStyle:{color:'#dce7e2'}},axisTick:{show:false},axisLabel:{color:'#526f86',fontSize:12,interval:Math.max(0,Math.floor(labels.length/4)-1)}},yAxis:{type:'value',min:Math.max(0,Math.floor(Math.min(...values)/10)*10-5),max:Math.min(100,Math.ceil(Math.max(...values)/10)*10+5),splitNumber:4,axisLine:{show:false},axisTick:{show:false},axisLabel:{formatter:'{value}%',color:'#526f86',fontSize:12},splitLine:{lineStyle:{color:'#e5ede8'}}},series:[{type:'line',data:values,smooth:.22,symbol:'circle',symbolSize:7,lineStyle:{color:'#08704e',width:3},itemStyle:{color:'#08704e'},areaStyle:{color:'rgba(34,145,98,.08)'},markPoint:{symbol:'circle',symbolSize:16,label:{show:true,formatter:`${current.toFixed(0)}%`,position:'top',color:'#ed6a00',fontSize:12,fontWeight:700},itemStyle:{color:'#ed6a00'},data:[{coord:[values.length-1,current]}]}}]},true);}
onMounted(()=>{chart=echarts.init(root.value!);observer=new ResizeObserver(()=>chart?.resize());observer.observe(root.value!);render();});watch(()=>props.device,render,{deep:true});onBeforeUnmount(()=>{observer?.disconnect();chart?.dispose();});
</script>
<template><div ref="root" class="zone-trend-chart" role="img" aria-label="Soil moisture trend over the last twelve hours"></div></template>
