import {describe,it,expect} from 'vitest';
import {seed,forecast,tick,interruptTasks,type Task} from '../server/domain';
function task():Task{return {id:'t',requestId:'r',type:'water',volume:70,createdAt:'2026-09-19T00:00:00Z',status:'pending',results:[{deviceId:'A01',status:'pending',progress:0,delivered:0,message:'PENDING',at:'2026-09-19T00:00:00Z',initialMoisture:32,targetMoisture:65,maxVolume:70,elapsedSeconds:0,maxDurationSeconds:12}]};}
describe('deterministic simulation',()=>{
 it('builds varied 24h history for the new topology',()=>{const s=seed(new Date('2026-09-19T00:00:00Z'));expect(s.devices[0].history).toHaveLength(25);expect(s.devices.every(device=>device.online)).toBe(true);expect(s.devices[2].cropId).toBe('corn');const changes=s.devices[0].history.slice(1).map((point,index)=>Number((point.value-s.devices[0].history[index].value).toFixed(2)));expect(new Set(changes).size).toBeGreaterThan(5);});
 it('hotter and brighter conditions accelerate depletion',()=>{const s=seed();const mild=forecast(s.devices[5],18,0,s.clock),hot=forecast(s.devices[5],36,12,s.clock);expect(hot.future[12].value).toBeLessThan(mild.future[12].value);expect(hot.crossing).not.toBeNull();expect(mild.crossing).toBeNull();});
 it('baseline is unchanged by scenario parameters, bounds start at current value',()=>{const s=seed();const a=forecast(s.devices[0],28,6,s.clock),b=forecast(s.devices[0],30,8,s.clock);expect(a.baselineRate).toBe(b.baselineRate);expect(a.future[0].low).toBe(a.future[0].high);expect(a.future.every(p=>p.low<=p.value&&p.value<=p.high)).toBe(true);});
 it('rejects offline and insufficient histories',()=>{const s=seed();s.devices[2].online=false;expect(()=>forecast(s.devices[2],28,6,s.clock)).toThrow();s.devices[0].history=[];expect(()=>forecast(s.devices[0],28,6,s.clock)).toThrow();});
 it('preserves clock, tasks, and readings while paused',()=>{const s=seed();s.tasks=[task()];s.paused=true;const before=structuredClone(s);tick(s);expect(s).toEqual(before);});
 it('waters until target moisture and delivers once only',()=>{const s=seed();s.devices[0].moisture=32;s.tasks=[task()];tick(s);expect(s.tasks[0].status).toBe('running');for(let i=0;i<10&&s.tasks[0].status==='running';i++)tick(s);expect(s.tasks[0].status).toBe('success');expect(s.tasks[0].results[0].message).toBe('TARGET_MOISTURE_REACHED');expect(s.tasks[0].results[0].progress).toBe(100);expect(s.devices[0].moisture).toBe(65);const delivered=s.tasks[0].results[0].delivered;expect(delivered).toBeLessThanOrEqual(70);tick(s);expect(s.tasks[0].results[0].delivered).toBe(delivered);expect(s.devices[0].moisture).toBeLessThan(65);});
 it('offline interrupts partial delivery and retains delivered volume',()=>{const s=seed();s.devices[0].moisture=32;s.tasks=[task()];tick(s);tick(s);s.devices[0].online=false;tick(s);expect(s.tasks[0].status).toBe('failed');expect(s.tasks[0].results[0].delivered).toBe(10);expect(s.tasks[0].results[0].message).toBe('DEVICE_OFFLINE');});
 it('restart fails incomplete tasks without resuming delivery',()=>{const s=seed();s.devices[0].moisture=32;s.tasks=[task()];tick(s);tick(s);interruptTasks(s);tick(s);expect(s.tasks[0].results[0].message).toBe('SERVER_RESTART');expect(s.tasks[0].results[0].delivered).toBe(10);});
});
